# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    - id: black
      name: black
      entry: black ./
      language: python
      types: [python]
      language_version: python3.10

-   repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: pylint dth/
      language: system
      types: [python]
      require_serial: true
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
          "--exit-zero", # Don't fail pre commit
        ]

-   repo: local
    hooks:
    - id: pytest_e2e
      name: pytest
      entry: python -m pytest --cov=. --cov-config=./tests/config/.coveragerc_e2e ./tests/tests_e2e.py
      language: system
      types: [python]
      pass_filenames: false
      always_run: true

-   repo: local
    hooks:
    - id: pytest_unit
      name: pytest
      entry: python -m pytest --cov=. --cov-config=./tests/config/.coveragerc_unit ./tests/tests_unit.py
      language: system
      types: [python]
      pass_filenames: false
      always_run: true
