# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: tests

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'

    - name: Set up environment
      run: |
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        pytest --cov=. --cov-config=./tests/config/.coveragerc_unit ./tests/tests_unit.py

    - name: Run e2e tests
      run: |
        pytest --cov=. --cov-config=./tests/config/.coveragerc_e2e ./tests/tests_e2e.py
