# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Donjon to Homebrewery (example)

on: 
  workflow_dispatch

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv shell
    - name: Run example file
      run: |
        python convert_donjon_to_homebrewery.py example.json -gm https://imgur.com/cpy3lBq.png
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: homebrewery.txt
    

