# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: generate-homebrewery-text

on: 
  workflow_dispatch:
    inputs: 
      filename:
        type: string
        description: Link to donjon JSON file (see README)
        required: true
      gm_map:
        type: string
        description: URL where gm map is hosted
        required: true
      player_map:
        type: string
        description: URL where player map is hosted
        required: true

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'

    - name: Set up environment
      run: |
        pip install -r requirements.txt

    - name: Environmental Variables
      run: |
        touch .env
        echo OPENAI_API_KEY='${{ secrets.OPENAI_API_KEY }}' >> .env
        echo OPENAI_ORG='${{ secrets.OPENAI_ORG }}' >> .env
        echo OPENAI_PROJECT_ID='${{ secrets.OPENAI_PROJECT_ID }}' >> .env

    - name: Generate homebrewery file
      run: |
        curl -L "${{ github.event.inputs.filename }}" -o donjon.json
        python convert_donjon_to_homebrewery.py donjon.json -gm ${{ github.event.inputs.gm_map }} -p ${{ github.event.inputs.player_map }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: homebrewery.txt
        path: ./homebrewery.txt
    

